### ISSUE TITLE
unable to compile example for ESP32

### ISSUE THREAD

**Issue by blassbasti** [forkineye/ESPAsyncE131#4]
Hi,

I'm a bit of a newbie with how arduino and the libraries work together and can't get the example in this fork to work.

I know that ESP32 uses `#include <WiFi.h>` instead of `#include <ESP8266WiFi.h>` like the ESP8266 does but I still can't compile the code.

This is what the console says:

> Multiple libraries were found for "WiFi.h"
 Used: C:\Users\bbsup\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\libraries\WiFi
In file included from C:\Users\bbsup\AppData\Local\Temp\arduino_modified_sketch_74994\ESP8266_Test.ino:22:0:
Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
C:\Users\bbsup\Documents\Arduino\libraries\ESP_Async_E1.31/ESPAsyncE131.h:23:25: fatal error: ESPAsyncUDP.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board TTGO LoRa32-OLED V1.

**Comment by forkineye** [comment]
Looks like you need to update your repo.  ESP8266_Test.ino has been replaced.  An ESP32 build should reference AsnycUDP and not ESPAsyncUDP.

**Comment by mic159** [comment]
@forkineye looks like you have not done a release with the ESP32 support.
Could you please do a release and put it up on the arduino library manager?

On the releases page it says the are 39 commits since the last release
https://github.com/forkineye/ESPAsyncE131/releases

![image](https://user-images.githubusercontent.com/849426/67094172-f3748e00-f1fe-11e9-94db-583d0f5d82bc.png)
